# Build settings
markdown: kramdown

# Theme default
theme: jekyll-theme-cayman

# Site default
title: Escornabot
description: Escornabot es un proyecto de código/hardware abierto cuyo objetivo es acercar la robótica y la programación a los niños y niñas.
keywords: escornabot, robótica, programación

